"""paciente municipio Nullable

Revision ID: 727a9df549ff
Revises: 
Create Date: 2025-09-20 21:26:16.818130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '727a9df549ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cid10_id'), table_name='cid10')
    op.create_index(op.f('ix_cid10_codigo'), 'cid10', ['codigo'], unique=False)
    op.drop_column('cid10', 'id')
    op.drop_constraint(op.f('pacientes_ibfk_2'), 'pacientes', type_='foreignkey')
    op.create_foreign_key(None, 'pacientes', 'cid10', ['cid10_id'], ['codigo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pacientes', type_='foreignkey')
    op.create_foreign_key(op.f('pacientes_ibfk_2'), 'pacientes', 'cid10', ['cid10_id'], ['id'])
    op.add_column('cid10', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_cid10_codigo'), table_name='cid10')
    op.create_index(op.f('ix_cid10_id'), 'cid10', ['id'], unique=False)
    # ### end Alembic commands ###
